[package]
name = "spectre-bridge-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
web3 = "0.18.0"
borsh = "0.9.3"
serde = "1.0.136"
serde_json = "1.0.79"
eth_client = { path = "eth_client" }
tokio = "1.17.0"

[dependencies.redis]
version = "*"
git = "https://github.com/mitsuhiko/redis-rs.git"