[package]
name = "spectre-bridge-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.0.0-pre.7"
rocket = "0.5.0-rc.1"
web3 = "0.18.0"
borsh = "0.9.3"
serde = "1.0.136"
serde_json = "1.0.79"
near-lake-framework = { git = "https://github.com/near/near-lake-framework", tag = "v0.2.0" }
tokio = "1.17.0"
near-primitives = "0.12.0"
near-jsonrpc-primitives = "0.12.0"
uint = { version = "0.8.3", default-features = false }
config = "0.13.1"
url = "2.2.2"
http-client = "6.5.1"
http-types = "2.12.0"
transfer-event-logs = { git = "https://github.com/spectrebridge/spectre-bridge-common.git", branch = "main" }
near_client = { path = "near_client" }
eth_client = { path = "eth_client" }

[dependencies.redis]
version = "*"
git = "https://github.com/mitsuhiko/redis-rs.git"
