[package]
name = "spectre-bridge-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.0.0-pre.7"
rocket = "0.5.0-rc.1"
web3 = "0.18.0"
borsh = "0.9.3"
serde = "1.0.136"
serde_json = "1.0.79"
near-lake-framework = "0.3.0"
tokio = "1.17.0"
near-jsonrpc-client = "0.3.0"
near-primitives = "0.12.0"
near-jsonrpc-primitives = "0.12.0"
uint = { version = "0.8.3", default-features = false }
config = "0.13.1"
url = "2.2.2"
http-client = "6.5.1"
http-types = "2.12.0"
near_client = { path = "near_client" }
eth_client = { path = "eth_client" }
redis = { version = "0.21.5", features = ["tokio-comp"] }
spectre-bridge-common = { path = "./spectre-bridge-common" }
assert-json-diff = "2.0.1"
reqwest = "0.11.10"reqwest = "0.11.10"