profit_thershold: 10000

redis:
 url: "redis://127.0.0.1/"

near:
 private_key: ""
 rpc_url: "https://rpc.testnet.near.org"
 contract_address: "transfer.spectrebridge.testnet"

eth:
 private_key: ""
 rpc_url: "https://goerli.infura.io/v3/ba5fd6c86e5c4e8c9b36f3f5b4013f7a"
 contract_address: "0x4F04E2dbEB74016CE52F5A6D136C65AE0C61e236"