version: '3.8'

services:
  spectre-bridge-service:
    build: .
    ports:
      - 443:3000
    depends_on:
      - redis
    networks:
      - bridge

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: 6380
        protocol: tcp
        mode: host
    volumes:
        - redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    network_mode: host
    networks:
      - bridge

volumes:
  redis_data:
    
networks:
  bridge:
