name: spectre-bridge-service test automatically

on:
  push:
    branches: [main]
  pull_request:
    branches: ["!main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.submodulessh }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  --manifest-path ./Cargo.toml --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  --manifest-path ./Cargo.toml -- -A clippy::too-many-arguments -D warnings
      - run: cargo build
      - run: cargo test
