name: tf apply manual

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export AWS_ACCESS_KEY_ID="${{secrets.AWS_ACCESS_KEY_ID_VALUE}}"
          export AWS_SECRET_ACCESS_KEY="${{secrets.AWS_SECRET_ACCESS_KEY_VALUE}}"
          export AWS_REGION="${{secrets.AWS_REGION_VALUE}}"
          terraform init; 
          terraform apply -var ssh_pub_key="${{secrets.SPECTRESSHPUB}}" --auto-approve
      
            
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Terraform store tfstate"
          branch: "feature/tf"
          file_pattern: "*.tfstate"
